### PR TITLE
Add autocomplete to help

### PR DESCRIPTION
**Pull request by microbit-rosslowe**
- Add information on autocomplete to help
- Add screenshot GIFs of the autocomplete process

### CODE REVIEW

**Comment by microbit-carlos** [comment]
Is this PR ready for review? Has anybody been assigned to review?

**Comment by microbit-rosslowe** [comment]
@microbit-carlos We've discussed this in stand-up and Mark has reviewed the copy when adding to a support article. This is ready for a final review in context.

**Comment by microbit-rosslowe** [comment]
@microbit-mark Would you be able to review this in the context of help.html (formatting, images, how well the copy flows)?

**Comment by microbit-mark** [comment]
I think the copy is good. My feeling is that the paragraph probably needs to come under the 'Text window' section though as it's not a menu button feature.

**Comment by microbit-rosslowe** [comment]
Change made @microbit-mark, what do you think?

**Comment by microbit-mark** [comment]
LGTM

**Pull request merged**
